# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76e9fb825e0b8170b331a21c382e9711e654bf2b41f345da05316676cb9e5c3f0c369ad771a3c7637b0eb242025ed8bd13157376203215c90df604b885fad38f

test:
  secret_key_base: f5e6cbd1e5556b905984868667146f95c59496254a6691d06c26b8d0b8ecdbba6b9dc2b99a2d30d6502676fc5fd12af4ec762849c16cfd48ce4c304da4efd5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
